### ISSUE TITLE
1.21.1

### ISSUE THREAD

**Issue by ditt0132** [flowerinsnow-lights-opensource/MineEnter#14]
please! i think it can be changed by fabric.mod.json but i tried porting on some mod and many error came because mappings! idk more about it

**Comment by flowerinsnowdh** [comment]
Sorry, I haven't checked the issues for a long time.

Planned for tomorrow

**Comment by flowerinsnowdh** [comment]
https://github.com/flowerinsnow-lights-opensource/MineEnter/releases/tag/v5.4.0-beta.1
